name: Build CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
    - name: Build for Windows
      run: ./build.bat
    - uses: actions/upload-artifact@v2
      with:
        name: FastImageCompare
        path: main.exe
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: ls
    - name: Make executable
      run: chmod +x ./build.sh
    - name: Build for Linux
      run: ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: FastImageCompare
        path: main
