name: Build CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
    - name: Build for Windows
      run: ./build.bat
    - uses: actions/upload-artifact@v2
      with:
        name: FastImageCompareWin64
        path: main.exe
  build-linux64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Make executable
      run: chmod +x ./build.sh
    - name: Build for Linux
      run: ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: FastImageCompareLinux64
        path: main
  build-linuxarm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Make executable
      run: chmod +x ./build.sh
    - name: Install G++ aarch64
      run: sudo apt install g++-aarch64-linux-gnu
    - name: Build for Linux
      run: ./build_arm64.sh
    - uses: actions/upload-artifact@v2
      with:
        name: FastImageCompareArm64
        path: main
